<section>
          <h3>Ajouter une catégorie</h3>
       
            
    <form action="/Res03ProjetFinalV2/check-creer-categorie" method="post">
      <label for="name">Nom de la catégorie :</label>
            <input type="text" name="name" id="name" required>
      <label for="description">Description :</label>
            <textarea name="description" id="description"></textarea>
      <footer>
            <input type="submit" value="Ajouter la catégorie">
      </footer>
    </form>
</section>
