<section>
      <header>
          <h2>Supprimer une Catégorie</h1>
      </header>
       
            
    <form action="/Res03ProjetFinalV2/supprimer-categorie" method="post">
      <label for="name">Nom de la catégorie :</label>
            <input type="text" name="name" id="name" required>
      <label for="description">Description :</label>
            <textarea name="description" id="description"></textarea>
      <footer>
            <input type="submit" value="Supprimer la catégorie">
      </footer>
    </form>
</section>
