<header id="yep-head">  
            <nav>  
                <h1>E-techMax</h1> 
                <a href="/Res03ProjetFinalV2/"><img src="/Res03ProjetFinalV2/assets/styles/images/ETechMax.png" alt="logo-société"></a>  
                <ul>  
                    <li>  
                        <a href="/Res03ProjetFinalV2/">Accueil</a> 
                    </li>  
                    <li>  
                        <a href="/Res03ProjetFinalV2/produits">Produits</a>  
                    </li>
                    <li>  
                        <a href="/Res03ProjetFinalV2/connexion">Connexion/Inscription</a>  
                    </li>  
                </ul>  
            </nav>  
        </header>